       - name: Fetch Nifty500 close
        run: python fetch_prices.py --universe nifty500 --symbols_csv universes/nifty500.csv --period 2y --auto_adjust
       - name: DMA breadth Nifty500
        run: python breadth_dma.py --universe nifty500 --close_csv data/nifty500/close.csv --fast 50 --slow 200

      # Later add this block for Nifty750
      # - name: Fetch Nifty750 close
      #   run: python fetch_prices.py --universe nifty750 --symbols_csv universes/nifty750.csv --period 2y --auto_adjust
      #
      # - name: DMA breadth Nifty750
      #   run: python breadth_dma.py --universe nifty750 --close_csv data/nifty750/close.csv --fast 50 --slow 200
